/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package project

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appCanGreet() {
        val classUnderTest = App
        assertNotNull(classUnderTest.greet(), "app should have a greeting")
    }
}
